/**
*
* University of Illinois/NCSA
* Open Source License
*
* Copyright (c) 2008, NCSA.  All rights reserved.
*
* Developed by:
* The Automated Learning Group
* University of Illinois at Urbana-Champaign
* http://www.seasr.org
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal with the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject
* to the following conditions:
*
* Redistributions of source code must retain the above copyright
* notice, this list of conditions and the following disclaimers.
*
* Redistributions in binary form must reproduce the above copyright
* notice, this list of conditions and the following disclaimers in
* the documentation and/or other materials provided with the distribution.
*
* Neither the names of The Automated Learning Group, University of
* Illinois at Urbana-Champaign, nor the names of its contributors may
* be used to endorse or promote products derived from this Software
* without specific prior written permission.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE
* FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
* CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
*
*/

package org.meandre.components.tapor;

import java.io.InputStreamReader;
import java.io.BufferedReader;

import java.net.URL;

import org.apache.commons.httpclient.HostConfiguration;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.SimpleHttpConnectionManager;
import org.apache.commons.httpclient.methods.PostMethod;

import org.meandre.annotations.Component;

import org.meandre.core.ComponentContext;
import org.meandre.core.ComponentContextException;
import org.meandre.core.ComponentContextProperties;
import org.meandre.core.ComponentExecutionException;
import org.meandre.core.ExecutableComponent;

@Component(creator="Lily Dong",
           description="Demonstrate how to construct a interface to " +
           "consume rest service.",
           name="Rest Service Client",
           tags="rest service")

public class ListWords implements ExecutableComponent {
    /** When ready for execution.
     *
     * @param cc The component context
     * @throws ComponentExecutionException An exeception occurred during execution
     * @throws ComponentContextException Illigal access to context
     */
    public void execute(ComponentContext cc) throws
    ComponentExecutionException,ComponentContextException {
    	try {
    		String loc = "http://tapor1-dev.mcmaster.ca/~restserv/html/concordance";//"http://tapor1-dev.mcmaster.ca/~restserv/html/listwords";
    		URL url = new URL(loc);

    		HostConfiguration hostConfig = new HostConfiguration();
        	hostConfig.setHost(url.getHost(), url.getPort());
        	HttpClient httpClient = new HttpClient(new SimpleHttpConnectionManager());
        	httpClient.setHostConfiguration(hostConfig);
        	PostMethod postMethod = new PostMethod(loc);

        	String htmlInput = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Frameset//EN\" \"http://www.w3.org/TR/html4/frameset.dtd\">\n";
htmlInput += "<!--NewPage-->\n";
htmlInput += "<HTML>\n";
htmlInput += "<HEAD>\n";
htmlInput += "<meta name=\"collection\" content=\"exclude\">\n";

htmlInput += "<!-- Generated by javadoc on Wed Aug 11 07:30:38 PDT 2004-->\n";
htmlInput += "<TITLE>\n";
htmlInput += "Java 2 Platform SE 5.0\n";
htmlInput += "</TITLE>\n";
htmlInput += "<SCRIPT type=\"text/javascript\">\n";
htmlInput += "targetPage = \"\" + window.location.search;\n";
htmlInput += "if (targetPage != \"\" && targetPage != \"undefined\")\n";
htmlInput += "targetPage = targetPage.substring(1);\n";
htmlInput += "if (targetPage.indexOf(\":\") != -1)\n";
htmlInput += "targetPage = \"undefined\";\n";
htmlInput += "function loadFrames() {\n";
htmlInput += "if (targetPage != \"\" && targetPage != \"undefined\")\n";
htmlInput += "top.classFrame.location = top.targetPage;\n";
htmlInput += "}\n";
htmlInput += "</SCRIPT>\n";
htmlInput += "<NOSCRIPT>\n";
htmlInput += "</NOSCRIPT>\n";
htmlInput += "</HEAD>\n";
htmlInput += "<FRAMESET cols=\"20%,80%\" title=\"\" onLoad=\"top.loadFrames()\">\n";
htmlInput += "<FRAMESET rows=\"30%,70%\" title=\"\" onLoad=\"top.loadFrames()\">\n";
htmlInput += "<FRAME src=\"overview-frame.html\" name=\"packageListFrame\" title=\"All Packages\">\n";

htmlInput += "<FRAME src=\"allclasses-frame.html\" name=\"packageFrame\" title=\"All classes and interfaces (except non-static nested types)\">\n";
htmlInput += "</FRAMESET>\n";
htmlInput += "<FRAME src=\"overview-summary.html\" name=\"classFrame\" title=\"Package, class and interface descriptions\" scrolling=\"yes\">\n";
htmlInput += "<NOFRAMES>\n";
htmlInput += "<H2>\n";
htmlInput += "Frame Alert</H2>\n";

htmlInput += "<P>\n";
htmlInput += "This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client.\n";
htmlInput += "<BR>\n";
htmlInput += "Link to<A HREF=\"overview-summary.html\">Non-frame version.</A>\n";
htmlInput += "</NOFRAMES>\n";
htmlInput += "</FRAMESET>\n";
htmlInput += "</HTML>\n";


        	/*postMethod.addParameter("htmlInput", htmlInput);
        	postMethod.addParameter("htmlTag", "body");
        	postMethod.addParameter("listOption", "all");
        	postMethod.addParameter("optionSelection", "glasgow");
        	postMethod.addParameter("sorting", "2");
        	postMethod.addParameter("outFormat", "4");*/

  			postMethod.addParameter("htmlInput", htmlInput);
  			postMethod.addParameter("htmlTag", "body");;
			postMethod.addParameter("pattern", "*");
			postMethod.addParameter("context", "1");
			postMethod.addParameter("contextlength", "5");
			postMethod.addParameter("outFormat", "4");

        	httpClient.executeMethod(postMethod);

        	BufferedReader in = new BufferedReader(
        			new InputStreamReader(
        					postMethod.getResponseBodyAsStream()));
        	String line = null;
        	while((line = in.readLine()) != null)
        		System.out.println(line);

        	in.close();

    	}catch(Exception e) {
    		throw new ComponentExecutionException(e);
    	}
    }

	/**
	 * Call at the end of an execution flow.
	 */
	public void initialize(ComponentContextProperties ccp) {
	}

	/**
	 * Called when a flow is started.
	 */
	public void dispose(ComponentContextProperties ccp) {
	}
}
